Introduce Espresso tests framework and several general tests (#654)
* Introduce Espresso test framework and several general tests

It's time to add some tests.

Our code was not made with unit tests in mind and most of the errors are
in the interaction between components, so testing UI looks like a way to go.

Each test will be launched with a clean state. The drawback is that each test
takes considerable amount of time - several seconds.

Http requests are mocked with predefined content, if there is no content
- the 404 code is returned.

* ci: Enable CI for integration tests

Since Android emulators is not something that github supports out
of the box - non-zero amount of time is spent on emulators setup.

* Use ConditionWatcher for testing notifications

It's all timing based...

* Clear popups before each UI test

Application may have crashed in previous test or some
popup may be there for whatever reason.

* Use simple drag and drop test until recycler view tests are fixed

* Use latest stable gradle plugin

* Upgrade action-android to 0.0.7

* Turn of animations for instrumentated ci tests

* Increase timeout of test wait policies

This seems to be necessary for slow emulators.

* Disable animation in gradle test options

* Upgrade androidx.test to 1.3.0-rc01 and espresso to 3.3.0-rc01

* Fix IllegalStateException in ui lang tests

FATAL EXCEPTION: main
Process: net.programmierecke.radiodroid2, PID: 6697
java.lang.IllegalStateException: Fragment FragmentPlayerSmall{e8a6bff} (02bf954e-9388-4c8d-972e-98eee9d7bfa1)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:869)
	at net.programmierecke.radiodroid2.FragmentPlayerSmall.fullUpdate(FragmentPlayerSmall.java:226)
	at net.programmierecke.radiodroid2.FragmentPlayerSmall.setRole(FragmentPlayerSmall.java:176)
	at net.programmierecke.radiodroid2.ActivityMain$4.onStateChanged(ActivityMain.java:256)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1089)
	at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:1505)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

* Run UI notification tests only on APIs 26+

Consistently does not work on API 21:

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at net.programmierecke.radiodroid2.tests.UINotificationTests.playback_ShouldPause_OnPauseFromNotification(UINotificationTests.java:128)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at net.programmierecke.radiodroid2.tests.CustomTestRunner.onStart(CustomTestRunner.java:43)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)

* Skip undo action tests on API 21

For some reason they often fail with:

java.lang.RuntimeException: Wait for view with id is <net.programmierecke.radiodroid2:id/snackbar_action> to match (with string from resource id: <2131820607> and is displayed on the screen to the user) - took more than 20000 ms.
	at net.programmierecke.radiodroid2.tests.utils.conditionwatcher.ConditionWatcher.waitForCondition(ConditionWatcher.java:68)
	at net.programmierecke.radiodroid2.tests.utils.conditionwatcher.ViewMatchWaiter.toMatch(ViewMatchWaiter.java:37)
	at net.programmierecke.radiodroid2.tests.UIHistoryFragmentTest.stationInHistory_ShouldBeDeleted_WithSwipeRight(UIHistoryFragmentTest.java:127)

Co-authored-by: Marc K <morckx@gmail.com>