Fix espresso tests failure on CI
1) Recently instrumented CI started to fail with:
 Error: Unable to process command '::set-env name=ANDROID_HOME,::/Users/runner/android-sdk' successfully.

2) Bumping of androidx.test:runner androidx.test:rules resulted in an error:
 AAPT: error: attribute android:forceQueryable not found.

3) .test.BuildConfig doesn't contain configs set in gradle

4) Starting of the instrumented app stucked somewhere after a bump of
   com.squareup.okhttp3:mockwebserver for unknown reason, revert it for
   now.